# CORS

# quarkus.http.cors.enabled=false
# quarkus.http.cors.origins=http://localhost:4200

# %dev.quarkus.http.cors.enabled=false

# Banco
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=123456
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/oficina-crm

# Hibernate
%dev.quarkus.hibernate-orm.log.sql=true
%dev.quarkus.hibernate-orm.log.format-sql=true
%dev.quarkus.hibernate-orm.log.highlight-sql=true
%dev.quarkus.hibernate-orm.log.jdbc-warnings=true

# quarkus.hibernate-orm.database.generation=validate
# jakarta.persistence.schema-generation.database.action=validate


# Flyway
quarkus.flyway.migrate-at-start=true
quarkus.flyway.validate-at-start=true
quarkus.flyway.schemas=core,iam
quarkus.flyway.default-schema=core
quarkus.flyway.create-schemas=true
